
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button SnapScreenButton;

	private global::Gtk.Label TopLabel;

	private global::Gtk.Image ImageCanvasPic;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Events = ((global::Gdk.EventMask)(252));
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Events = ((global::Gdk.EventMask)(252));
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.SnapScreenButton = new global::Gtk.Button();
		this.SnapScreenButton.WidthRequest = 150;
		this.SnapScreenButton.HeightRequest = 60;
		this.SnapScreenButton.CanFocus = true;
		this.SnapScreenButton.Name = "SnapScreenButton";
		this.SnapScreenButton.UseUnderline = true;
		this.SnapScreenButton.Label = global::Mono.Unix.Catalog.GetString("Snap Screen");
		this.fixed1.Add(this.SnapScreenButton);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.SnapScreenButton]));
		w1.X = 195;
		w1.Y = 96;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.TopLabel = new global::Gtk.Label();
		this.TopLabel.Name = "TopLabel";
		this.TopLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Sreen Snap Region");
		this.fixed1.Add(this.TopLabel);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.TopLabel]));
		w2.X = 187;
		w2.Y = 39;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ImageCanvasPic = new global::Gtk.Image();
		this.ImageCanvasPic.WidthRequest = 800;
		this.ImageCanvasPic.HeightRequest = 500;
		this.ImageCanvasPic.Name = "ImageCanvasPic";
		this.fixed1.Add(this.ImageCanvasPic);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ImageCanvasPic]));
		w3.X = 192;
		w3.Y = 278;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1206;
		this.DefaultHeight = 886;
		this.Show();
		this.SnapScreenButton.Clicked += new global::System.EventHandler(this.OnSnapScreenButtonClicked);
	}
}
